config/routes.rb
Rails.application.routes.draw do
  resources :newdays
  resources :news
  resources :posts
  root "newdays#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/new.rb
class New < ApplicationRecord
end

app/models/newday.rb
class Newday < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/newdays_controller.rb
class NewdaysController < ApplicationController
  before_action :set_newday, only: %i[ show edit update destroy ]

  # GET /newdays or /newdays.json
  def index
    @newdays = Newday.all
  end

  # GET /newdays/1 or /newdays/1.json
  def show
  end

  # GET /newdays/new
  def new
    @newday = Newday.new
  end

  # GET /newdays/1/edit
  def edit
  end

  # POST /newdays or /newdays.json
  def create
    @newday = Newday.new(newday_params)

    respond_to do |format|
      if @newday.save
        format.html { redirect_to newday_url(@newday), notice: "Newday was successfully created." }
        format.json { render :show, status: :created, location: @newday }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @newday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newdays/1 or /newdays/1.json
  def update
    respond_to do |format|
      if @newday.update(newday_params)
        format.html { redirect_to newday_url(@newday), notice: "Newday was successfully updated." }
        format.json { render :show, status: :ok, location: @newday }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @newday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newdays/1 or /newdays/1.json
  def destroy
    @newday.destroy

    respond_to do |format|
      format.html { redirect_to newdays_url, notice: "Newday was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newday
      @newday = Newday.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def newday_params
      params.require(:newday).permit(:title, :date, :mood, :doing, :picture)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[ show edit update destroy ]

  # GET /news or /news.json
  def index
    @news = New.all
  end

  # GET /news/1 or /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = New.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news or /news.json
  def create
    @news = New.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_url(@news), notice: "New was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_url(@news), notice: "New was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_url, notice: "New was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = New.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:title, :date, :mood, :doing, :picture)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :date, :mood, :doing, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newdays_helper.rb
module NewdaysHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jeannejapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dosis&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/newdays/_form.html.erb
<%= form_with(model: newday) do |form| %>
  <% if newday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(newday.errors.count, "error") %> prohibited this newday from being saved:</h2>

      <ul>
        <% newday.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <%= form.label :date %>
    <%= form.date_field :date, as: :date, html5: true %>
  </div>

  <div class="field">
    <%= form.label :mood %>
    <%= form.text_field :mood %>
  </div>

  <div class="field">
    <%= form.label :actions %>
    <%= form.text_area :doing %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_area :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/newdays/edit.html.erb
<h1>Modifier la journée :</h1>

<%= render 'form', newday: @newday %>

<%= link_to 'Voir', @newday %> |
<%= link_to 'Retour', newdays_path %>

app/views/newdays/index.html.erb
<p id="notice"><%= notice %></p>

<div class="back">
<h1 class="mytitle">Days on Rails</h1>
<h3>L'application qui vous permet de noter et de raconter votre journée ! </h3>
<div class="text-center"><div class="btn green"> <%= link_to 'Nouvelle journée', new_newday_path %> </div></div>
</div>

<h2>Mes archives :</h2>

<div class="cols-1 cols-md-4 g-4 main">
  <% @newdays.each do |newday| %>
    <div class="col">
      <%= newday.title %>
      <%= newday.date %>
      <%= link_to 'Voir', newday %>
      <%= link_to 'Modifier', edit_newday_path(newday) %>
      <%= link_to 'Supprimer', newday, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>
</div>

app/views/newdays/new.html.erb
<h1 class="titleform">Ma nouvelle journée :</h1>

<%= render 'form', newday: @newday %>

<%= link_to 'Retour', newdays_path %>

app/views/newdays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @newday.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @newday.date %>
</p>

<p>
  <strong>Mood:</strong>
  <%= @newday.mood %>
</p>

<p>
  <strong>Doing:</strong>
  <%= @newday.doing %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @newday.picture %>
</p>

<%= link_to 'Modifier', edit_newday_path(@newday) %> |
<%= link_to 'Retour', newdays_path %>

app/views/news/_form.html.erb
<%= form_with(model: news) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% news.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" placeholder="Le titre de ma journée...">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field" placeholder="Ma météo interne...">
    <%= form.label :mood %>
    <%= form.text_field :mood %>
  </div>

  <div class="field">
    <%= form.label :doing %>
    <%= form.text_area :doing placeholder="Ce que j'ai fait aujourd'hui..." %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_area :picture image_tag %>
  </div>

  <div class="action">
    <%= form.submit, label:"creer" %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_path %>

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>

<h1>News</h1>

<div class="cols-1 cols-md-12 g-12 main">
  <% @news.each do |news| %>
    <div class="col-12">
      <div class="title"> <%= news.title%></div>
      <div class="date">  <%= news.date %></div>
      <%= link_to 'Show', news %>
      <%= link_to 'Edit', edit_news_path(news) %>
      <%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Tu es sûr(e) ?' } %>
    </div>
  <% end %>
</div>

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @news.date %>
</p>

<p>
  <strong>Mood:</strong>
  <%= @news.mood %>
</p>

<p>
  <strong>Doing:</strong>
  <%= @news.doing %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @news.picture %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :mood %>
    <%= form.text_field :mood %>
  </div>

  <div class="field">
    <%= form.label :doing %>
    <%= form.text_area :doing %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_area :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Mood</th>
      <th>Doing</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.date %></td>
        <td><%= post.mood %></td>
        <td><%= post.doing %></td>
        <td><%= post.picture %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @post.date %>
</p>

<p>
  <strong>Mood:</strong>
  <%= @post.mood %>
</p>

<p>
  <strong>Doing:</strong>
  <%= @post.doing %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @post.picture %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>